### ISSUE TITLE
USER STORY: Submit a Poll Response

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/love-running#1]
In order to **provide my opinion with regards to a certain running topic or event** as a **user**, I can **select and submit an answer from the poll**

## Acceptance Criteria
- Acceptance Criteria 1: A poll includes a menu with a selection of topics
- Acceptance Criteria 2: A poll includes submit button
- Acceptance Criteria 3: A poll includes a text area to allow users to add comments.

## Tasks List
- [ ] Create a radio button menu with selected topics
- [ ] Add submit button to the poll
- [ ] Add text area HTML element as part of poll structure

**Comment by miloszmisiek** [comment]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**

### Acceptance Criteria
- Acceptance Criteria 1: A poll includes a button to hide users' identities.
- Acceptance Criteria 2: The name displayed for hidden identity is "anonymous"
## Tasks List
- [ ] Create a tick-box button to select anonymous entry
- [ ] Identify default value in code as "anonymous" for hidden identity comments
